// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiRAwaHmnZIWC0qHADNxXXdPZluOwBrRA',
    appId: '1:509849925790:web:a655e55e0980b4958b238f',
    messagingSenderId: '509849925790',
    projectId: 'easy-order-8e1a2',
    authDomain: 'easy-order-8e1a2.firebaseapp.com',
    storageBucket: 'easy-order-8e1a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoU5uxvOha78NWmeOpxSE8qBvRgvYQX8I',
    appId: '1:509849925790:android:12a99051aae036058b238f',
    messagingSenderId: '509849925790',
    projectId: 'easy-order-8e1a2',
    storageBucket: 'easy-order-8e1a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUAzkPyOYqWxfCGlH8UtTfDec-GQ2A5as',
    appId: '1:509849925790:ios:1f6df0a978330d658b238f',
    messagingSenderId: '509849925790',
    projectId: 'easy-order-8e1a2',
    storageBucket: 'easy-order-8e1a2.firebasestorage.app',
    iosBundleId: 'com.sakthi.easyOrder',
  );
}
